### ISSUE TITLE
On /users, the UI doesn't check for an existing user in the users table prior to letting you add user.

### ISSUE THREAD

**Issue by robertmcatee** [Open-Case-Filing/Lexodus#22]
On /users, the UI doesn't check for an existing user in the users table prior to letting you add user.

This causes a duplicate request to be submitted , which throws a SQL exception. (which also throws the raw stack trace back to the user). 

example;

[Add User] 

error running server function: Failed to execute SQL: Error::QueryFailed("Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: Some(Error), code: SqlState(E23505), message: \"duplicate key value violates unique constraint \\\"users_username_key\\\"\", detail: Some(\"Key (username)=(johnsmith) already exists.\"), hint: None, position: None, where_: None, schema: Some(\"public\"), table: Some(\"users\"), column: None, datatype: None, constraint: Some(\"users_username_key\"), file: Some(\"nbtinsert.c\"), line: Some(666), routine: Some(\"_bt_check_unique\") }) }")

![image](https://github.com/user-attachments/assets/1d6f23b1-8a04-4b01-9e07-1970ea08e237)

**Comment by tyler-harpool** [comment]
We no longer passed the auth check. 
    let auth_context = use_context::<AuthContext>().expect("Failed to get AuthContext");
Looks like the error is correct, that the username has been taken. Error is valid.
Also important to note, that this is incorrectly labeled. This is how you promote a user to a specific role.
